config/routes.rb
Rails.application.routes.draw do

	get '/packages/subregion_options' => 'packages#subregion_options'

	devise_scope :user do
		post '/user/registrations/choose' => 'user/registrations#choose'
	end

	devise_for :users, :controllers => {
		:registrations => "user/registrations"
	}

	resources :users
	resources :packages

	resources :packages, only: [:show] do
		resources :public_reservations, except: [:destroy]
	end

  resources :users_public_reservations, only: [:new, :index, :create, :show]

 	resources :packages, except: [:index] do
		resources :private_reservations, except: [:show, :update, :destroy]
	end

	resources :private_reservations, only: [:show, :update, :destroy]
 


  root to: "pages#index"


end

app/models/private_reservation.rb
class PrivateReservation < ActiveRecord::Base

	belongs_to :user
	belongs_to :package


end

app/controllers/concerns/private_reservations_controller.rb
class PrivateReservationsController < ApplicationController
	# before_action :authenticate_user!

	def new
		@private_reservation = PrivateReservation.new
	end

	def create
		@private_reservation = PrivateReservation.new(private_reservation_params)

		if @private_reservation.save
			
		else

		end
	end

	private
		def private_reservation_params
			params.require(:private_reservation).permit(:package_id, :user_id, :head_count, :start_date, :end_date)
		end

end

app/controllers/private_reservations_controller.rb
class PrivateReservationsController < ApplicationController
	def new
		@private_reservation = PrivateReservation.new
	end

	def create
		package = Package.find(params[:package_id])
		private_reservation = package.private_reservations.new(private_reservation_params)
		private_reservation.user_id = current_user.id

		if private_reservation.save
			redirect_to "/private_reservations/#{private_reservation.id}"
		else
			render :new
		end
	end

	def show
		@private_reservation = PrivateReservation.find(params[:id])
	end

	def edit
		@private_reservation = PrivateReservation.find(params[:id])
	end

	def update
		private_reservation = PrivateReservation.find(params[:id])
		if private_reservation.update(private_reservation_params)
			redirect_to "/private_reservations/#{private_reservation.id}"
		else
			render :edit
		end

	end

	def destroy
		PrivateReservation.destroy(params[:id])
		redirect_to "/users/#{current_user.id}"
	end

	private
		def private_reservation_params
			params.require(:private_reservation).permit(:head_count, :start_date, :end_date)
		end
end

app/helpers/private_reservations_helper.rb
module PrivateReservationsHelper
end

app/views/private_reservations/_form.html.erb
<div class="form-group">
		<%= f.label :head_count %>
		<%= f.number_field :head_count ,placeholder:"Head Count", min: 1, class:'form-control' %>
	</div>

	<div class="form-group">
		<%= f.label :start_date %>
		<%= f.text_field :start_date, placeholder:"Start Date", id:'from', class:'form-control' %>
	</div>

	<div class="form-group">
		<%= f.label :end_date %>
		<%= f.text_field :end_date, placeholder:"End date", id:'to', class:'form-control' %>
	</div>

	<div class="form-group">
		<%= f.submit "Submit", class:"btn btn-success btn-lg" %>
</div>

app/views/private_reservations/edit.html.erb
<div class="container" , id="private-form-edit">

	<h1>PrivateReservations#Edit</h1>

		<%= form_for @private_reservation, method: :patch, url: private_reservation_path do |f| %>
			<%= render "form", f: f %>
		<% end %>

		<%= link_to "Cancel", @private_reservation %>
	

</div>

app/views/private_reservations/new.html.erb
<div class="container">
	<div class="private-reservation">

		<h1>Private Reservations</h1>

		<%= form_for @private_reservation, url: package_private_reservations_path do |f| %>
			<%= render "form", f: f %>
		<% end %>
	</div>
</div>

app/views/private_reservations/show.html.erb
<!-- PrivateReservations#Show -->

<h1><%= @private_reservation.package.title %> Private Reservation</h1>
<p><%= @private_reservation.package.description %></p><br/>

<li><strong>Head Count:</strong> <%= @private_reservation.head_count %></li>
<li><strong>Start Date:</strong> <%= @private_reservation.start_date %></li>
<li><strong>End Date:</strong> <%= @private_reservation.end_date %></li>

<% if current_user == @private_reservation.user %>
	<%= link_to "Edit Reservation", edit_package_private_reservation_path(@private_reservation.package, @private_reservation) %><br/>

	<%= link_to "Cancel Reservation", private_reservation_path(@private_reservation), method: :delete, data: {confirm: 'Are you sure?'} %>
<% end %>