config/routes.rb
Rails.application.routes.draw do

	get '/packages/subregion_options' => 'packages#subregion_options'

	devise_scope :user do
		post '/user/registrations/choose' => 'user/registrations#choose'
	end

	devise_for :users, :controllers => {
		:registrations => "user/registrations"
	}

	resources :users
	resources :packages

	resources :packages, only: [:show] do
		resources :public_reservations, except: [:destroy]
	end

  resources :users_public_reservations, only: [:new, :index, :create, :show]

 	resources :packages, except: [:index] do
		resources :private_reservations, except: [:show, :update, :destroy]
	end

	resources :private_reservations, only: [:show, :update, :destroy]
 


  root to: "pages#index"


end

app/models/users_public_reservation.rb
class UsersPublicReservation < ActiveRecord::Base

	belongs_to :user
	belongs_to :public_reservation

 	validate :full_participants
 	validate :register?

 	def full_participants
  	if self.public_reservation.status == 'Full' || self.public_reservation.status == 'Closed'
  		errors.add(:user_id, "This tour is closed.")
  	end
  end

  def register?
  	invalid = UsersPublicReservation.find_by('user_id = ? AND public_reservation_id = ?', self.user_id, self.public_reservation.id)
  
  	if invalid
  		errors.add(:user_id, "You have applied for this tour")
  	end

  end

end

app/controllers/users_public_reservations_controller.rb
class UsersPublicReservationsController < ApplicationController

	def index

	end

	def new
		# @user_public_reservation = UsersPublicReservation.new
		@public_reservation = PublicReservation.find(params[:public_reservation_id])
		@package = @public_reservation.package
		@client_token = Braintree::ClientToken.generate

	end

	def create

		@public_reservation = PublicReservation.find(params[:checkout_form][:public_reservation_id])

		@package = @public_reservation.package

		amount = params[:checkout_form][:public_price]
		nonce_from_the_client = params[:checkout_form][:payment_method_nonce]

		render action: :new and return unless nonce_from_the_client

		@result = Braintree::Transaction.sale(
				:amount => amount,
				:payment_method_nonce => nonce_from_the_client,
				:options => {
						:submit_for_settlement => true
					}
			)


		
		if @result.success? 
			transaction = @result.transaction

			@user_public_reservation = current_user.users_public_reservations.create(reservation_params)

			flash[:success] = 'Your payment has been successfully processed. Enjoy your trip!'

			redirect_to @user_public_reservation

		else 

			flash.now[:alert] = "Something went wrong while processing your transaction. Please try again!"
			render :new

		end

	end

	def show
		@user_public_reservation = UsersPublicReservation.find(params[:id])
		@public_reservation = @user_public_reservation.public_reservation
		@package = @public_reservation.package
	end

	private

	def reservation_params
		params.require(:checkout_form).permit(:public_reservation_id)
	end

end

app/helpers/users_public_reservations_helper.rb
module UsersPublicReservationsHelper
end

app/views/users_public_reservations/backup_new.html.erb
<% if flash[:alert] %>

	<div class="alert alert-danger">

		<%= flash[:alert] %>

	</div>

<% end %>

<h3>Payment</h3>

<div class="credit-card-form">

	<%= form_for :checkout_form, url: users_public_reservations_path, html: {id:"checkout-form"} do |f|%>
		
	  <div class="field">
			<p>Tour: <%= @package.title %></p>
		</div>

		<div class="field">
			<%= f.hidden_field :public_reservation_id, :value => @public_reservation.id %>
		</div>

		<div class="field">
	    <%= f.hidden_field :public_price, value: @public_reservation.public_price %>
	  </div>

	  <div id="error-message"></div>

	  <div id="dropin-container"></div>

	  <%= f.label :card_number, "Card Number"%>
	  <div class="hosted-field" id="card-number"></div>
	  
	  <%= f.label :cvv, "CVV"%>
	  <div class="hosted-field" id="cvv"></div>

	  <%= f.label :expiration_date, "Expiration_date"%>
	  <div class="hosted-field" id="expiration-date"></div>

	  <%= f.hidden_field "payment_method_nonce" %>

		<%= f.submit "Proceed", disabled: true, class: "btn btn-primary", id: "submit-payment" %>

	<% end %>

</div>

	 <script src="https://js.braintreegateway.com/web/3.3.0/js/client.min.js"></script>

	 <script src="https://js.braintreegateway.com/web/3.3.0/js/hosted-fields.min.js"></script>

app/views/users_public_reservations/new.html.erb
<% if flash[:alert] %>

  <div class="alert alert-warning">

    <%= flash[:alert] %>

  </div>

<% end %>


<div class="panel panel-default bootstrap-basic">
  <div class="panel-heading">
    <h3 class="panel-title">Enter Card Details</h3>
  </div>

    <%= form_for :checkout_form, url: users_public_reservations_path, html: {id:"checkout-form", class:"panel-body"} do |f|%>

    <div class="row">

    <div class="field">
      <%= f.hidden_field :public_reservation_id, :value => @public_reservation.id %>
    </div>

    <div class="field">
      <%= f.hidden_field :public_price, value: @public_reservation.public_price %>
    </div>

      <div class="form-group col-md-12 col-sm-12 col-xs-12", id="card-num">
        <label class="control-label">Card Number</label>
        <!--  Hosted Fields div container -->
        <div class="form-control" id="card-number"></div>
        <span class="helper-text"></span>
      </div>
      <div class="form-group col-md-12 col-sm-12 col-xs-12">
        <div class="row">
          <label class="control-label col-xs-12">Expiration Date</label>
          <div class="col-md-6 col-sm-6 col-xs-6", id="hosted-month">
            <!--  Hosted Fields div container -->
            <div class="form-control" id="expiration-month"></div>
          </div>
          <div class="col-md-6 col-sm-6 col-xs-6", id="hosted-year">
            <!--  Hosted Fields div container -->
            <div class="form-control" id="expiration-year"></div>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="form-group col-md-6 col-xs-6", id="security-code">

        <label class="control-label">Security Code</label>

        <!--  Hosted Fields div container -->
        <div class="form-control" id="cvv"></div>
      </div>
   </div>

    <%= f.hidden_field "payment_method_nonce" %>

    <%= button_tag(type: 'submit', class: "btn btn-success btn-lg center-block", id:"submit-payment") do %>
    		Pay with <span id="card-type">Card</span>
    	<% end %>

    <% end %>

    </div>

<!-- Load the required client component. -->
<script src="https://js.braintreegateway.com/web/3.3.0/js/client.min.js"></script>

<!-- Load Hosted Fields component. -->
<script src="https://js.braintreegateway.com/web/3.3.0/js/hosted-fields.min.js"></script>

<script>
  
  $(document).ready(function(){

  var form = document.querySelector('#checkout-form');
  var authorization = '<%= @client_token %>'


braintree.client.create({
  authorization: authorization
}, function (err, clientInstance) {
  if (err) {
    console.error(err);
    return;
  }

  braintree.hostedFields.create({
    client: clientInstance,
    styles: {
      'input': {
        'font-size': '14px',
        'font-family': 'helvetica, tahoma, calibri, sans-serif',
        'color': '#3a3a3a'
      },
      ':focus': {
        'color': 'black'
      }
    },
    fields: {
      number: {
        selector: '#card-number',
        placeholder: '4111 1111 1111 1111'
      },
      cvv: {
        selector: '#cvv',
        placeholder: '123'
      },
      expirationMonth: {
        selector: '#expiration-month',
        placeholder: 'MM'
      },
      expirationYear: {
        selector: '#expiration-year',
        placeholder: 'YY'
      },
    }
  }, function (err, hostedFieldsInstance) {
    if (err) {
      console.error(err);
      return;
    }

    hostedFieldsInstance.on('validityChange', function (event) {
      var field = event.fields[event.emittedBy];

      if (field.isValid) {
        if (event.emittedBy === 'expirationMonth' || event.emittedBy === 'expirationYear') {
          if (!event.fields.expirationMonth.isValid || !event.fields.expirationYear.isValid) {
            return;
          }
        } else if (event.emittedBy === 'number') {
          $('#card-number').next('span').text('');
        }
                
        // Apply styling for a valid field
        $(field.container).parents('.form-group').addClass('has-success');
      } else if (field.isPotentiallyValid) {
        // Remove styling  from potentially valid fields
        $(field.container).parents('.form-group').removeClass('has-warning');
        $(field.container).parents('.form-group').removeClass('has-success');
        if (event.emittedBy === 'number') {
          $('#card-number').next('span').text('');
        }
      } else {
        // Add styling to invalid fields
        $(field.container).parents('.form-group').addClass('has-warning');
        // Add helper text for an invalid card number
        if (event.emittedBy === 'number') {
          $('#card-number').next('span').text('Looks like this card number has an error.');
        }
      }
    });

    hostedFieldsInstance.on('cardTypeChange', function (event) {
      // Handle a field's change, such as a change in validity or credit card type
      if (event.cards.length === 1) {
        $('#card-type').text(event.cards[0].niceType);
      } else {
        $('#card-type').text('Card');
      }
    });

      form.addEventListener('submit', function (event) {
        event.preventDefault();

      hostedFieldsInstance.tokenize(function (err, payload) {
        if (err) {
          console.error(err);
          return;
        }

         document.querySelector('input[name="checkout_form[payment_method_nonce]"]').value = payload.nonce;

          form.submit();

        // This is where you would submit payload.nonce to your server
      });
    });
  });
});
});
</script>

app/views/users_public_reservations/show.html.erb
<div class="container">

	<% if flash[:success] %>

		<div class="alert alert-success">

			<%= flash[:success] %>

		</div>

	<% end %>

	<h3>Confirmation <span id="count_down"> <%= @public_reservation.count_down %></span></h3>

	<p>Reservation id: <%= @user_public_reservation.id%></p>

	<p>Tour: <%= link_to @package.title, package_path(@package), method: 'get' %></p>

	<p>Guide: <%= @package.user.username %></p>

	<p>Type: Open Tour </p>

	<p>Start date: <%= @public_reservation.start_date %></p>

	<p>End date: <%= @public_reservation.end_date %></p>

	<p>Payment: RM<%= @public_reservation.public_price %></p>

</div>