config/routes.rb
Rails.application.routes.draw do

	get '/packages/subregion_options' => 'packages#subregion_options'

	devise_scope :user do
		post '/user/registrations/choose' => 'user/registrations#choose'
	end

	devise_for :users, :controllers => {
		:registrations => "user/registrations"
	}

	resources :users
	resources :packages

	resources :packages, only: [:show] do
		resources :public_reservations, except: [:destroy]
	end

  resources :users_public_reservations, only: [:new, :index, :create, :show]

 	resources :packages, except: [:index] do
		resources :private_reservations, except: [:show, :update, :destroy]
	end

	resources :private_reservations, only: [:show, :update, :destroy]
 


  root to: "pages#index"


end

app/models/public_reservation.rb
class PublicReservation < ActiveRecord::Base

	has_many :users, through: :users_public_reservations
	has_many :users_public_reservations

	belongs_to :package

  validates :start_date, :end_date, :public_price, presence: true
 


  def count_participants
  	self.users_public_reservations.count
  	
  end

  def status

  	max_participants = self.package.head
  	participants = self.count_participants

  	if self.start_date <= Date.today
  		return 'Closed'

  	elsif participants >= max_participants
  		return 'Full'

  	else 
  		return 'Open'

  	end

  end

  def valid?(id)
    self.users_public_reservations.find_by('user_id =?',id).nil?
  end

  def count_down
    result = (self.start_date - Date.today).to_i

    if result > 1
      return result.to_s + ' days'
    elsif result == 1
      return '1 day'
    else
      return 'Expired'
    end

  end

end

app/controllers/public_reservations_controller.rb
class PublicReservationsController < ApplicationController
  
  before_action :find_package, only: [:new, :create, :show, :edit, :update]
  before_action :find_public_reservation, only: [:show, :edit, :update]
  before_action :authenticate_tour_guide!, only: [:new, :create, :edit, :update]

  def new
    @public_reservation = PublicReservation.new
  end

  def create
    @public_reservation = @package.public_reservations.new(reservation_params)

    if @public_reservation.save

      redirect_to @package
    else
      render 'new'
    end

  end

  def show
    @user = @package.user
  end

  def edit
  end

  def update
    
    if @public_reservation.update(reservation_params)
      redirect_to package_public_reservation_path(params[:package_id], @public_reservation.id)
    else
      render 'edit'
    end

  end

  private

  def find_package
    @package = Package.find(params[:package_id])
  end

  def find_public_reservation
    @public_reservation = PublicReservation.find(params[:id])
  end

  def reservation_params
    params.require(:public_reservation).permit(:public_price, :start_date, :end_date)
  end

  def authenticate_tour_guide!
    redirect_to root_path unless current_user.role == "tour_guide"
  end

end

app/helpers/public_reservations_helper.rb
module PublicReservationsHelper
end

app/views/public_reservations/edit.html.erb
<h1>PublicReservations#edit</h1>
<p>Find me in app/views/public_reservations/edit.html.erb</p>

app/views/public_reservations/index.html.erb
<h1>PublicReservations#index</h1>
<p>Find me in app/views/public_reservations/index.html.erb</p>

app/views/public_reservations/new.html.erb
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

	<% if @public_reservation.errors.full_messages.any? %>
		<div class="alert alert-danger">
		  <% @public_reservation.errors.full_messages.each do |error_message| %>

		    <%= error_message %><br> 

		  <% end %>
	  </div>
	<% end %>
  


<div class="container">
	<div class="public-reservation">
		<div class="public-reservation-title">
			<h2>Make a public tour for <%= @package.title %></h2>
		</div>
			<%= form_for [@package, @public_reservation] do |f| %>
			<div class="form-group">
				<%= f.label :public_price, "Price per pax" %>
				<%= f.text_field :public_price, placeholder:"Price per pax", class:"form-control" %>
			</div>

			<div class="form-group">
				<%= f.label :start_date %>
				<%= f.text_field :start_date, placeholder:"Click to select", id:'from', class:"form-control" %>
			</div>
				
			<div class="form-group">
				<%= f.label :end_date %>
				<%= f.text_field :end_date, placeholder:"Click to select", id:'to', class:"form-control" %>
			</div>

				<%= f.submit :submit, class:"btn btn-success btn-lg" %>

			<% end %>
			
	</div>
</div>	

app/views/public_reservations/show.html.erb
<div class="container">

	<h1><%= link_to "#{@package.title} - #{@package.day} day(s) tour", package_path(@package)%></h1>

	<h4>Open Tour <span class=<%= @public_reservation.status %>>(<%= @public_reservation.status %>)</span></h4>

	<p>Tour Guide: <%= @package.user.username %></p>
	<p>Start date: <%= @public_reservation.start_date %></p>
	<p>End date: <%= @public_reservation.end_date %></p>
	<p>Price: RM<%= @public_reservation.public_price %></p>
	<p>Participants: <%= @public_reservation.count_participants %>/<%=@package.head %></p>

	<% if @public_reservation.status == 'Open' && @public_reservation.valid?(current_user.id) %>

		<%= link_to "Book now", new_users_public_reservation_path(:public_reservation_id => @public_reservation.id), method: 'get', class: "btn btn-primary" %>

	<% end %>

</div>