config/routes.rb
Rails.application.routes.draw do

	get '/packages/subregion_options' => 'packages#subregion_options'

	devise_scope :user do
		post '/user/registrations/choose' => 'user/registrations#choose'
	end

	devise_for :users, :controllers => {
		:registrations => "user/registrations"
	}

	resources :users
	resources :packages

	resources :packages, only: [:show] do
		resources :public_reservations, except: [:destroy]
	end

  resources :users_public_reservations, only: [:new, :index, :create, :show]

 	resources :packages, except: [:index] do
		resources :private_reservations, except: [:show, :update, :destroy]
	end

	resources :private_reservations, only: [:show, :update, :destroy]
 


  root to: "pages#index"


end

app/views/layouts/_footer.html.erb
<footer id="footerWrapper" class="<%= current_page?(root_path) ? "footer-transparent" : "footer-margin" %>">
	<section id="mainFooter">
		<div class="container">
			<div class="row">
				<div class="col-sm-5">
					<div class="footerWidget">

						<%= link_to root_path, method: "get" do  %><%= image_tag("logo_white.png") %><% end %> 
						<address>
							<p><i class=""></i>AG-7, Glomac Damansara, Jalan Damansara,<br>
								 Tmn Tun Dr Ismail, 60000, Malaysia<br>
								<i class="icon-phone"></i>&nbsp;TEL: 03-9000 8000 <br>
								<i class="icon-mail-alt"></i>&nbsp;<a href="mailto:tripkaki@example.com">tripkaki@example.com</a> </p>
							</address>
						</div>
					</div>
				<div class="col-sm-4">
					<div class="footerWidget">
						<ul>
							<h5>About</h5>
							<a href="/"><li>About Us</li></a>
							<a href="/"><li>Contact Us</li></a>
							<a href="/"><li>Company</li></a>
							<a href="/"><li>Privacy Policy</li></a>
						</ul>
					</div>
				</div>
					<div class="col-sm-3">
						<div class="footerWidget">
							<h5>Follow us, we are social</h5>
							<div class="socialNetwork">
								<a href="/" class="tips" title="follow me on Facebook"><i class="fa fa-facebook"></i></a>
								<a href="/" class="tips" title="follow me on Twitter"><i class="fa fa-twitter"></i></a>
								<a href="#" class="tips" title="follow me on Google+"><i class="fa fa-google-plus"></i></a>
								<a href="#" class="tips" title="follow me on Linkedin"><i class="fa fa-linkedin"></i></a>
							</div>     
						</div>
					</div>
				</div>
			</div>
		</section>
		<section id="footerRights">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<p>Copyright © 2016 <a href="/" target="blank">TripKaki</a> / All rights reserved.</p>
					</div>

				</div>
			</div>
		</section>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-custom <%= "navbar-transparent" if current_page?(root_path)  %>">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class:"navbar-brand", method: "get" do  %><%= image_tag("logo_white.png") %><% end %> 
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      <% if user_signed_in? && current_user.role == "tour_guide" %>
          <li><%= link_to "Create a new package", new_package_path, method: "get", class:"new_package-btn" %></li>
        <% end %>
        <% if user_signed_in? %>
          <li><%= link_to "Search Package" , packages_path, method: "get", class:"search_package-btn"  %></li>
        <% end %> 
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
        <% if user_signed_in? %>
          <li><%= link_to "Profile", current_user, class:"profile-btn" %></li>
          <li>
          <%= link_to('Logout', destroy_user_session_path, :method => :delete, class:"logout-btn") %>        
          </li>
        <% else %>
          <li>
          <%= link_to('Login', new_user_session_path, class:"login-btn")  %>  
         </li>
          <li><%= link_to "Sign Up" , new_user_registration_path, method: "get", class:"signup-btn" %></li>
       <% end %> 
        <!-- <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li> -->
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tripkaki</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    "https://fonts.googleapis.com/css?family=Lato" %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
   <!-- Latest compiled and minified CSS -->

</head>
<a href="javascript:" id="return-to-top"><i class="fa fa-angle-up" aria-hidden="true"></i></a>

<%= render "layouts/navbar" %>
<%= yield %>
<%= render "layouts/footer" %>

</body>
</html>